/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/headers.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>

#include "3d_viewer_my/affins.h"
#include "3d_viewer_my/obj_reader.h"
#define TOL 0.000001
#define OK 1
START_TEST(affins_move_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {40, -20, -20, 40, -20, 20, 0, -20, 20};
  count_vector = 3;
  difference diff = {20, 0, 0, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_move_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {0, -20, -20, 0, -20, 20, -40, -20, 20};
  count_vector = 3;
  difference diff = {-20, 0, 0, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_move_3) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {40, 0, 0, 40, 0, 40, 0, 0, 40};
  count_vector = 3;
  difference diff = {20, 20, 20, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_size_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {40, -40, -40, 40, -40, 40, -40, -40, 40};
  count_vector = 3;
  difference diff = {0, 0, 0, 2, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_x_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, -20, -20, 20, -20, 20, -20, -20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_x_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, 20, 20, 20, 20, -20, -20, 20, -20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, M_PI, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_x_3) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, 20, -20, 20, -20, -20, -20, -20, -20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, M_PI / 2, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_y_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, -20, -20, 20, -20, 20, -20, -20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_y_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {-20, -20, 20, -20, -20, -20, 20, -20, -20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, M_PI, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_y_3) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {-20, -20, -20, 20, -20, -20, 20, -20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, M_PI / 2, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_z_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, -20, -20, 20, -20, 20, -20, -20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_z_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {-20, 20, -20, -20, 20, 20, 20, 20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, 0, M_PI};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_rotation_z_3) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {20, 20, -20, 20, 20, 20, 20, -20, 20};
  count_vector = 3;
  difference diff = {0, 0, 0, 1, 0, 0, M_PI / 2};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_mult_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {80, -40, -40, 80, -40, 40, 0, -40, 40};
  count_vector = 3;
  difference diff = {20, 0, 0, 2, 0, 0, 0};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(affins_mult_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  vector origin_vectors[3] = {-40, 40, -40, -40, 40, 40, 40, 40, 40};
  count_vector = 3;
  difference diff = {0, 0, 0, 2, 0, 0, M_PI};
  vector *result = calloc(count_vector, sizeof(vector));
  recalculation(vectors, count_vector, result, diff);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(result[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(result[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(result[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(obj_reader_1) {
  vector *vectors;
  vector origin_vectors[8] = {20, -20, -20, 20,  -20, 20,  -20, -20,
                              20, -20, -20, -20, 20,  20,  -20, 20,
                              20, 20,  -20, 20,  20,  -20, 20,  -20};
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  ck_assert_int_eq(error, OK);
  ck_assert_int_eq(count_vector, 8);
  ck_assert_int_eq(count_surface, 12);
  for (int i = 0; i < count_vector; i++) {
    ck_assert_double_eq_tol(vectors[i].x, origin_vectors[i].x, TOL);
    ck_assert_double_eq_tol(vectors[i].y, origin_vectors[i].y, TOL);
    ck_assert_double_eq_tol(vectors[i].z, origin_vectors[i].z, TOL);
  }
}
END_TEST

START_TEST(obj_reader_2) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("dont_exist.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  // print_vector(vectors, count_vector);
  // print_surface(surface, count_surface);
  ck_assert_int_eq(error, 0);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, affins_move_1);
  tcase_add_test(tc1_1, affins_move_2);
  tcase_add_test(tc1_1, affins_move_3);
  tcase_add_test(tc1_1, affins_size_1);
  tcase_add_test(tc1_1, affins_rotation_x_1);
  tcase_add_test(tc1_1, affins_rotation_x_2);
  tcase_add_test(tc1_1, affins_rotation_x_3);
  tcase_add_test(tc1_1, affins_rotation_y_1);
  tcase_add_test(tc1_1, affins_rotation_y_2);
  tcase_add_test(tc1_1, affins_rotation_y_3);
  tcase_add_test(tc1_1, affins_rotation_z_1);
  tcase_add_test(tc1_1, affins_rotation_z_2);
  tcase_add_test(tc1_1, affins_rotation_z_3);
  tcase_add_test(tc1_1, affins_mult_1);
  tcase_add_test(tc1_1, affins_mult_2);
  tcase_add_test(tc1_1, obj_reader_1);
  tcase_add_test(tc1_1, obj_reader_2);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
