/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/headers.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <stdlib.h>

#include "3d_viewer_my/affins.h"
#include "3d_viewer_my/obj_reader.h"
#define TOL 0.000001
#define OK 1
START_TEST(obj_reader_1) {
  vector *vectors;
  surface_dot *surface;
  int count_vector = 0, count_surface = 0;
  int error = obj_read("test/test_cube.obj", &vectors, &surface, &count_vector,
                       &count_surface);
  // print_vector(vectors, count_vector);
  // print_surface(surface, count_surface);
  ck_assert_int_eq(error, OK);
  ck_assert_int_eq(count_vector, 8);
  ck_assert_int_eq(count_surface, 12);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, obj_reader_1);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
